- name: Install nginx
  hosts: web
  become: yes
  tasks:
  - name: Ensure nginx package is present
    apt:
      name: nginx
      state: present
  - name: text add
    lineinfile:
      dest: /var/www/html/index.nginx-debian.html
      regexp: '^(.*)Welcome to nginx!(.*)$'
      line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'
      backrefs: yes 
  - name: Ensure nginx service is started
    service:
      name: nginx
      state: started
